// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CIM.Message.proto

#include "CIM.Message.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace CIM {
namespace Message {
PROTOBUF_CONSTEXPR CIMMsgData::CIMMsgData(
    ::_pbi::ConstantInitialized)
  : from_nick_name_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , client_msg_id_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , msg_data_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , from_user_id_(uint64_t{0u})
  , to_session_id_(uint64_t{0u})
  , server_msg_id_(uint64_t{0u})
  , create_time_(0)
  , msg_type_(0)

  , session_type_(0)
{}
struct CIMMsgDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CIMMsgDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CIMMsgDataDefaultTypeInternal() {}
  union {
    CIMMsgData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CIMMsgDataDefaultTypeInternal _CIMMsgData_default_instance_;
PROTOBUF_CONSTEXPR CIMMsgDataAck::CIMMsgDataAck(
    ::_pbi::ConstantInitialized)
  : client_msg_id_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , from_user_id_(uint64_t{0u})
  , to_session_id_(uint64_t{0u})
  , server_msg_id_(uint64_t{0u})
  , res_code_(0)

  , session_type_(0)

  , create_time_(0){}
struct CIMMsgDataAckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CIMMsgDataAckDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CIMMsgDataAckDefaultTypeInternal() {}
  union {
    CIMMsgDataAck _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CIMMsgDataAckDefaultTypeInternal _CIMMsgDataAck_default_instance_;
PROTOBUF_CONSTEXPR CIMMsgDataReadAck::CIMMsgDataReadAck(
    ::_pbi::ConstantInitialized)
  : user_id_(uint64_t{0u})
  , session_id_(uint64_t{0u})
  , msg_id_(uint64_t{0u})
  , session_type_(0)
{}
struct CIMMsgDataReadAckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CIMMsgDataReadAckDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CIMMsgDataReadAckDefaultTypeInternal() {}
  union {
    CIMMsgDataReadAck _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CIMMsgDataReadAckDefaultTypeInternal _CIMMsgDataReadAck_default_instance_;
PROTOBUF_CONSTEXPR CIMMsgDataReadNotify::CIMMsgDataReadNotify(
    ::_pbi::ConstantInitialized)
  : user_id_(uint64_t{0u})
  , session_id_(uint64_t{0u})
  , msg_id_(uint64_t{0u})
  , session_type_(0)
{}
struct CIMMsgDataReadNotifyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CIMMsgDataReadNotifyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CIMMsgDataReadNotifyDefaultTypeInternal() {}
  union {
    CIMMsgDataReadNotify _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CIMMsgDataReadNotifyDefaultTypeInternal _CIMMsgDataReadNotify_default_instance_;
PROTOBUF_CONSTEXPR CIMGetLatestMsgIdReq::CIMGetLatestMsgIdReq(
    ::_pbi::ConstantInitialized)
  : user_id_(uint64_t{0u})
  , session_id_(uint64_t{0u})
  , session_type_(0)
{}
struct CIMGetLatestMsgIdReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CIMGetLatestMsgIdReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CIMGetLatestMsgIdReqDefaultTypeInternal() {}
  union {
    CIMGetLatestMsgIdReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CIMGetLatestMsgIdReqDefaultTypeInternal _CIMGetLatestMsgIdReq_default_instance_;
PROTOBUF_CONSTEXPR CIMGetLatestMsgIdRsp::CIMGetLatestMsgIdRsp(
    ::_pbi::ConstantInitialized)
  : latest_msg_id_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , user_id_(uint64_t{0u})
  , session_id_(uint64_t{0u})
  , session_type_(0)
{}
struct CIMGetLatestMsgIdRspDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CIMGetLatestMsgIdRspDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CIMGetLatestMsgIdRspDefaultTypeInternal() {}
  union {
    CIMGetLatestMsgIdRsp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CIMGetLatestMsgIdRspDefaultTypeInternal _CIMGetLatestMsgIdRsp_default_instance_;
PROTOBUF_CONSTEXPR CIMGetMsgByIdReq::CIMGetMsgByIdReq(
    ::_pbi::ConstantInitialized)
  : msg_id_list_()
  , user_id_(uint64_t{0u})
  , session_id_(uint64_t{0u})
  , session_type_(0)
{}
struct CIMGetMsgByIdReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CIMGetMsgByIdReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CIMGetMsgByIdReqDefaultTypeInternal() {}
  union {
    CIMGetMsgByIdReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CIMGetMsgByIdReqDefaultTypeInternal _CIMGetMsgByIdReq_default_instance_;
PROTOBUF_CONSTEXPR CIMGetMsgByIdRsp::CIMGetMsgByIdRsp(
    ::_pbi::ConstantInitialized)
  : msg_list_()
  , user_id_(uint64_t{0u})
  , session_id_(uint64_t{0u})
  , session_type_(0)
{}
struct CIMGetMsgByIdRspDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CIMGetMsgByIdRspDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CIMGetMsgByIdRspDefaultTypeInternal() {}
  union {
    CIMGetMsgByIdRsp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CIMGetMsgByIdRspDefaultTypeInternal _CIMGetMsgByIdRsp_default_instance_;
}  // namespace Message
}  // namespace CIM
namespace CIM {
namespace Message {

// ===================================================================

class CIMMsgData::_Internal {
 public:
};

CIMMsgData::CIMMsgData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:CIM.Message.CIMMsgData)
}
CIMMsgData::CIMMsgData(const CIMMsgData& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  from_nick_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    from_nick_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_from_nick_name().empty()) {
    from_nick_name_.Set(from._internal_from_nick_name(), 
      GetArenaForAllocation());
  }
  client_msg_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    client_msg_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_client_msg_id().empty()) {
    client_msg_id_.Set(from._internal_client_msg_id(), 
      GetArenaForAllocation());
  }
  msg_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    msg_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_msg_data().empty()) {
    msg_data_.Set(from._internal_msg_data(), 
      GetArenaForAllocation());
  }
  ::memcpy(&from_user_id_, &from.from_user_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&session_type_) -
    reinterpret_cast<char*>(&from_user_id_)) + sizeof(session_type_));
  // @@protoc_insertion_point(copy_constructor:CIM.Message.CIMMsgData)
}

inline void CIMMsgData::SharedCtor() {
from_nick_name_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  from_nick_name_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
client_msg_id_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  client_msg_id_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
msg_data_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  msg_data_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&from_user_id_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&session_type_) -
    reinterpret_cast<char*>(&from_user_id_)) + sizeof(session_type_));
}

CIMMsgData::~CIMMsgData() {
  // @@protoc_insertion_point(destructor:CIM.Message.CIMMsgData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CIMMsgData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  from_nick_name_.Destroy();
  client_msg_id_.Destroy();
  msg_data_.Destroy();
}

void CIMMsgData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void CIMMsgData::Clear() {
// @@protoc_insertion_point(message_clear_start:CIM.Message.CIMMsgData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  from_nick_name_.ClearToEmpty();
  client_msg_id_.ClearToEmpty();
  msg_data_.ClearToEmpty();
  ::memset(&from_user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&session_type_) -
      reinterpret_cast<char*>(&from_user_id_)) + sizeof(session_type_));
  _internal_metadata_.Clear<std::string>();
}

const char* CIMMsgData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 from_user_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          from_user_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string from_nick_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_from_nick_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // uint64 to_session_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          to_session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string client_msg_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_client_msg_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // uint64 server_msg_id = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          server_msg_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 create_time = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          create_time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .CIM.Def.CIMMsgType msg_type = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_msg_type(static_cast<::CIM::Def::CIMMsgType>(val));
        } else
          goto handle_unusual;
        continue;
      // .CIM.Def.CIMSessionType session_type = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_session_type(static_cast<::CIM::Def::CIMSessionType>(val));
        } else
          goto handle_unusual;
        continue;
      // bytes msg_data = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          auto str = _internal_mutable_msg_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CIMMsgData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CIM.Message.CIMMsgData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 from_user_id = 1;
  if (this->_internal_from_user_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_from_user_id(), target);
  }

  // string from_nick_name = 2;
  if (!this->_internal_from_nick_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_from_nick_name().data(), static_cast<int>(this->_internal_from_nick_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "CIM.Message.CIMMsgData.from_nick_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_from_nick_name(), target);
  }

  // uint64 to_session_id = 3;
  if (this->_internal_to_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_to_session_id(), target);
  }

  // string client_msg_id = 4;
  if (!this->_internal_client_msg_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_client_msg_id().data(), static_cast<int>(this->_internal_client_msg_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "CIM.Message.CIMMsgData.client_msg_id");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_client_msg_id(), target);
  }

  // uint64 server_msg_id = 5;
  if (this->_internal_server_msg_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(5, this->_internal_server_msg_id(), target);
  }

  // int32 create_time = 6;
  if (this->_internal_create_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_create_time(), target);
  }

  // .CIM.Def.CIMMsgType msg_type = 7;
  if (this->_internal_msg_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      7, this->_internal_msg_type(), target);
  }

  // .CIM.Def.CIMSessionType session_type = 8;
  if (this->_internal_session_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      8, this->_internal_session_type(), target);
  }

  // bytes msg_data = 9;
  if (!this->_internal_msg_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        9, this->_internal_msg_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CIM.Message.CIMMsgData)
  return target;
}

size_t CIMMsgData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CIM.Message.CIMMsgData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string from_nick_name = 2;
  if (!this->_internal_from_nick_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_from_nick_name());
  }

  // string client_msg_id = 4;
  if (!this->_internal_client_msg_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_client_msg_id());
  }

  // bytes msg_data = 9;
  if (!this->_internal_msg_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_msg_data());
  }

  // uint64 from_user_id = 1;
  if (this->_internal_from_user_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_from_user_id());
  }

  // uint64 to_session_id = 3;
  if (this->_internal_to_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_to_session_id());
  }

  // uint64 server_msg_id = 5;
  if (this->_internal_server_msg_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_server_msg_id());
  }

  // int32 create_time = 6;
  if (this->_internal_create_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_create_time());
  }

  // .CIM.Def.CIMMsgType msg_type = 7;
  if (this->_internal_msg_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_msg_type());
  }

  // .CIM.Def.CIMSessionType session_type = 8;
  if (this->_internal_session_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_session_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CIMMsgData::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const CIMMsgData*>(
      &from));
}

void CIMMsgData::MergeFrom(const CIMMsgData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CIM.Message.CIMMsgData)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_from_nick_name().empty()) {
    _internal_set_from_nick_name(from._internal_from_nick_name());
  }
  if (!from._internal_client_msg_id().empty()) {
    _internal_set_client_msg_id(from._internal_client_msg_id());
  }
  if (!from._internal_msg_data().empty()) {
    _internal_set_msg_data(from._internal_msg_data());
  }
  if (from._internal_from_user_id() != 0) {
    _internal_set_from_user_id(from._internal_from_user_id());
  }
  if (from._internal_to_session_id() != 0) {
    _internal_set_to_session_id(from._internal_to_session_id());
  }
  if (from._internal_server_msg_id() != 0) {
    _internal_set_server_msg_id(from._internal_server_msg_id());
  }
  if (from._internal_create_time() != 0) {
    _internal_set_create_time(from._internal_create_time());
  }
  if (from._internal_msg_type() != 0) {
    _internal_set_msg_type(from._internal_msg_type());
  }
  if (from._internal_session_type() != 0) {
    _internal_set_session_type(from._internal_session_type());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CIMMsgData::CopyFrom(const CIMMsgData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CIM.Message.CIMMsgData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CIMMsgData::IsInitialized() const {
  return true;
}

void CIMMsgData::InternalSwap(CIMMsgData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &from_nick_name_, lhs_arena,
      &other->from_nick_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &client_msg_id_, lhs_arena,
      &other->client_msg_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &msg_data_, lhs_arena,
      &other->msg_data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CIMMsgData, session_type_)
      + sizeof(CIMMsgData::session_type_)
      - PROTOBUF_FIELD_OFFSET(CIMMsgData, from_user_id_)>(
          reinterpret_cast<char*>(&from_user_id_),
          reinterpret_cast<char*>(&other->from_user_id_));
}

std::string CIMMsgData::GetTypeName() const {
  return "CIM.Message.CIMMsgData";
}


// ===================================================================

class CIMMsgDataAck::_Internal {
 public:
};

CIMMsgDataAck::CIMMsgDataAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:CIM.Message.CIMMsgDataAck)
}
CIMMsgDataAck::CIMMsgDataAck(const CIMMsgDataAck& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  client_msg_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    client_msg_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_client_msg_id().empty()) {
    client_msg_id_.Set(from._internal_client_msg_id(), 
      GetArenaForAllocation());
  }
  ::memcpy(&from_user_id_, &from.from_user_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&create_time_) -
    reinterpret_cast<char*>(&from_user_id_)) + sizeof(create_time_));
  // @@protoc_insertion_point(copy_constructor:CIM.Message.CIMMsgDataAck)
}

inline void CIMMsgDataAck::SharedCtor() {
client_msg_id_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  client_msg_id_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&from_user_id_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&create_time_) -
    reinterpret_cast<char*>(&from_user_id_)) + sizeof(create_time_));
}

CIMMsgDataAck::~CIMMsgDataAck() {
  // @@protoc_insertion_point(destructor:CIM.Message.CIMMsgDataAck)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CIMMsgDataAck::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  client_msg_id_.Destroy();
}

void CIMMsgDataAck::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void CIMMsgDataAck::Clear() {
// @@protoc_insertion_point(message_clear_start:CIM.Message.CIMMsgDataAck)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  client_msg_id_.ClearToEmpty();
  ::memset(&from_user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&create_time_) -
      reinterpret_cast<char*>(&from_user_id_)) + sizeof(create_time_));
  _internal_metadata_.Clear<std::string>();
}

const char* CIMMsgDataAck::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 from_user_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          from_user_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 to_session_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          to_session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string client_msg_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_client_msg_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // uint64 server_msg_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          server_msg_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .CIM.Def.CIMResCode res_code = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_res_code(static_cast<::CIM::Def::CIMResCode>(val));
        } else
          goto handle_unusual;
        continue;
      // .CIM.Def.CIMSessionType session_type = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_session_type(static_cast<::CIM::Def::CIMSessionType>(val));
        } else
          goto handle_unusual;
        continue;
      // int32 create_time = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          create_time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CIMMsgDataAck::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CIM.Message.CIMMsgDataAck)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 from_user_id = 1;
  if (this->_internal_from_user_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_from_user_id(), target);
  }

  // uint64 to_session_id = 2;
  if (this->_internal_to_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_to_session_id(), target);
  }

  // string client_msg_id = 3;
  if (!this->_internal_client_msg_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_client_msg_id().data(), static_cast<int>(this->_internal_client_msg_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "CIM.Message.CIMMsgDataAck.client_msg_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_client_msg_id(), target);
  }

  // uint64 server_msg_id = 4;
  if (this->_internal_server_msg_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(4, this->_internal_server_msg_id(), target);
  }

  // .CIM.Def.CIMResCode res_code = 5;
  if (this->_internal_res_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      5, this->_internal_res_code(), target);
  }

  // .CIM.Def.CIMSessionType session_type = 6;
  if (this->_internal_session_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      6, this->_internal_session_type(), target);
  }

  // int32 create_time = 7;
  if (this->_internal_create_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_create_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CIM.Message.CIMMsgDataAck)
  return target;
}

size_t CIMMsgDataAck::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CIM.Message.CIMMsgDataAck)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string client_msg_id = 3;
  if (!this->_internal_client_msg_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_client_msg_id());
  }

  // uint64 from_user_id = 1;
  if (this->_internal_from_user_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_from_user_id());
  }

  // uint64 to_session_id = 2;
  if (this->_internal_to_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_to_session_id());
  }

  // uint64 server_msg_id = 4;
  if (this->_internal_server_msg_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_server_msg_id());
  }

  // .CIM.Def.CIMResCode res_code = 5;
  if (this->_internal_res_code() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_res_code());
  }

  // .CIM.Def.CIMSessionType session_type = 6;
  if (this->_internal_session_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_session_type());
  }

  // int32 create_time = 7;
  if (this->_internal_create_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_create_time());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CIMMsgDataAck::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const CIMMsgDataAck*>(
      &from));
}

void CIMMsgDataAck::MergeFrom(const CIMMsgDataAck& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CIM.Message.CIMMsgDataAck)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_client_msg_id().empty()) {
    _internal_set_client_msg_id(from._internal_client_msg_id());
  }
  if (from._internal_from_user_id() != 0) {
    _internal_set_from_user_id(from._internal_from_user_id());
  }
  if (from._internal_to_session_id() != 0) {
    _internal_set_to_session_id(from._internal_to_session_id());
  }
  if (from._internal_server_msg_id() != 0) {
    _internal_set_server_msg_id(from._internal_server_msg_id());
  }
  if (from._internal_res_code() != 0) {
    _internal_set_res_code(from._internal_res_code());
  }
  if (from._internal_session_type() != 0) {
    _internal_set_session_type(from._internal_session_type());
  }
  if (from._internal_create_time() != 0) {
    _internal_set_create_time(from._internal_create_time());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CIMMsgDataAck::CopyFrom(const CIMMsgDataAck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CIM.Message.CIMMsgDataAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CIMMsgDataAck::IsInitialized() const {
  return true;
}

void CIMMsgDataAck::InternalSwap(CIMMsgDataAck* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &client_msg_id_, lhs_arena,
      &other->client_msg_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CIMMsgDataAck, create_time_)
      + sizeof(CIMMsgDataAck::create_time_)
      - PROTOBUF_FIELD_OFFSET(CIMMsgDataAck, from_user_id_)>(
          reinterpret_cast<char*>(&from_user_id_),
          reinterpret_cast<char*>(&other->from_user_id_));
}

std::string CIMMsgDataAck::GetTypeName() const {
  return "CIM.Message.CIMMsgDataAck";
}


// ===================================================================

class CIMMsgDataReadAck::_Internal {
 public:
};

CIMMsgDataReadAck::CIMMsgDataReadAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:CIM.Message.CIMMsgDataReadAck)
}
CIMMsgDataReadAck::CIMMsgDataReadAck(const CIMMsgDataReadAck& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&user_id_, &from.user_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&session_type_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
  // @@protoc_insertion_point(copy_constructor:CIM.Message.CIMMsgDataReadAck)
}

inline void CIMMsgDataReadAck::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&user_id_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&session_type_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
}

CIMMsgDataReadAck::~CIMMsgDataReadAck() {
  // @@protoc_insertion_point(destructor:CIM.Message.CIMMsgDataReadAck)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CIMMsgDataReadAck::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CIMMsgDataReadAck::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void CIMMsgDataReadAck::Clear() {
// @@protoc_insertion_point(message_clear_start:CIM.Message.CIMMsgDataReadAck)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&session_type_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
  _internal_metadata_.Clear<std::string>();
}

const char* CIMMsgDataReadAck::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 user_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          user_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 session_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 msg_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          msg_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .CIM.Def.CIMSessionType session_type = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_session_type(static_cast<::CIM::Def::CIMSessionType>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CIMMsgDataReadAck::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CIM.Message.CIMMsgDataReadAck)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 user_id = 1;
  if (this->_internal_user_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_user_id(), target);
  }

  // uint64 session_id = 2;
  if (this->_internal_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_session_id(), target);
  }

  // uint64 msg_id = 3;
  if (this->_internal_msg_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_msg_id(), target);
  }

  // .CIM.Def.CIMSessionType session_type = 4;
  if (this->_internal_session_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_session_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CIM.Message.CIMMsgDataReadAck)
  return target;
}

size_t CIMMsgDataReadAck::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CIM.Message.CIMMsgDataReadAck)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 user_id = 1;
  if (this->_internal_user_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_user_id());
  }

  // uint64 session_id = 2;
  if (this->_internal_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_session_id());
  }

  // uint64 msg_id = 3;
  if (this->_internal_msg_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_msg_id());
  }

  // .CIM.Def.CIMSessionType session_type = 4;
  if (this->_internal_session_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_session_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CIMMsgDataReadAck::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const CIMMsgDataReadAck*>(
      &from));
}

void CIMMsgDataReadAck::MergeFrom(const CIMMsgDataReadAck& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CIM.Message.CIMMsgDataReadAck)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_user_id() != 0) {
    _internal_set_user_id(from._internal_user_id());
  }
  if (from._internal_session_id() != 0) {
    _internal_set_session_id(from._internal_session_id());
  }
  if (from._internal_msg_id() != 0) {
    _internal_set_msg_id(from._internal_msg_id());
  }
  if (from._internal_session_type() != 0) {
    _internal_set_session_type(from._internal_session_type());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CIMMsgDataReadAck::CopyFrom(const CIMMsgDataReadAck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CIM.Message.CIMMsgDataReadAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CIMMsgDataReadAck::IsInitialized() const {
  return true;
}

void CIMMsgDataReadAck::InternalSwap(CIMMsgDataReadAck* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CIMMsgDataReadAck, session_type_)
      + sizeof(CIMMsgDataReadAck::session_type_)
      - PROTOBUF_FIELD_OFFSET(CIMMsgDataReadAck, user_id_)>(
          reinterpret_cast<char*>(&user_id_),
          reinterpret_cast<char*>(&other->user_id_));
}

std::string CIMMsgDataReadAck::GetTypeName() const {
  return "CIM.Message.CIMMsgDataReadAck";
}


// ===================================================================

class CIMMsgDataReadNotify::_Internal {
 public:
};

CIMMsgDataReadNotify::CIMMsgDataReadNotify(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:CIM.Message.CIMMsgDataReadNotify)
}
CIMMsgDataReadNotify::CIMMsgDataReadNotify(const CIMMsgDataReadNotify& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&user_id_, &from.user_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&session_type_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
  // @@protoc_insertion_point(copy_constructor:CIM.Message.CIMMsgDataReadNotify)
}

inline void CIMMsgDataReadNotify::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&user_id_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&session_type_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
}

CIMMsgDataReadNotify::~CIMMsgDataReadNotify() {
  // @@protoc_insertion_point(destructor:CIM.Message.CIMMsgDataReadNotify)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CIMMsgDataReadNotify::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CIMMsgDataReadNotify::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void CIMMsgDataReadNotify::Clear() {
// @@protoc_insertion_point(message_clear_start:CIM.Message.CIMMsgDataReadNotify)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&session_type_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
  _internal_metadata_.Clear<std::string>();
}

const char* CIMMsgDataReadNotify::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 user_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          user_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 session_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 msg_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          msg_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .CIM.Def.CIMSessionType session_type = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_session_type(static_cast<::CIM::Def::CIMSessionType>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CIMMsgDataReadNotify::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CIM.Message.CIMMsgDataReadNotify)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 user_id = 1;
  if (this->_internal_user_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_user_id(), target);
  }

  // uint64 session_id = 2;
  if (this->_internal_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_session_id(), target);
  }

  // uint64 msg_id = 3;
  if (this->_internal_msg_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_msg_id(), target);
  }

  // .CIM.Def.CIMSessionType session_type = 4;
  if (this->_internal_session_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_session_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CIM.Message.CIMMsgDataReadNotify)
  return target;
}

size_t CIMMsgDataReadNotify::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CIM.Message.CIMMsgDataReadNotify)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 user_id = 1;
  if (this->_internal_user_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_user_id());
  }

  // uint64 session_id = 2;
  if (this->_internal_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_session_id());
  }

  // uint64 msg_id = 3;
  if (this->_internal_msg_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_msg_id());
  }

  // .CIM.Def.CIMSessionType session_type = 4;
  if (this->_internal_session_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_session_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CIMMsgDataReadNotify::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const CIMMsgDataReadNotify*>(
      &from));
}

void CIMMsgDataReadNotify::MergeFrom(const CIMMsgDataReadNotify& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CIM.Message.CIMMsgDataReadNotify)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_user_id() != 0) {
    _internal_set_user_id(from._internal_user_id());
  }
  if (from._internal_session_id() != 0) {
    _internal_set_session_id(from._internal_session_id());
  }
  if (from._internal_msg_id() != 0) {
    _internal_set_msg_id(from._internal_msg_id());
  }
  if (from._internal_session_type() != 0) {
    _internal_set_session_type(from._internal_session_type());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CIMMsgDataReadNotify::CopyFrom(const CIMMsgDataReadNotify& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CIM.Message.CIMMsgDataReadNotify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CIMMsgDataReadNotify::IsInitialized() const {
  return true;
}

void CIMMsgDataReadNotify::InternalSwap(CIMMsgDataReadNotify* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CIMMsgDataReadNotify, session_type_)
      + sizeof(CIMMsgDataReadNotify::session_type_)
      - PROTOBUF_FIELD_OFFSET(CIMMsgDataReadNotify, user_id_)>(
          reinterpret_cast<char*>(&user_id_),
          reinterpret_cast<char*>(&other->user_id_));
}

std::string CIMMsgDataReadNotify::GetTypeName() const {
  return "CIM.Message.CIMMsgDataReadNotify";
}


// ===================================================================

class CIMGetLatestMsgIdReq::_Internal {
 public:
};

CIMGetLatestMsgIdReq::CIMGetLatestMsgIdReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:CIM.Message.CIMGetLatestMsgIdReq)
}
CIMGetLatestMsgIdReq::CIMGetLatestMsgIdReq(const CIMGetLatestMsgIdReq& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&user_id_, &from.user_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&session_type_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
  // @@protoc_insertion_point(copy_constructor:CIM.Message.CIMGetLatestMsgIdReq)
}

inline void CIMGetLatestMsgIdReq::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&user_id_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&session_type_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
}

CIMGetLatestMsgIdReq::~CIMGetLatestMsgIdReq() {
  // @@protoc_insertion_point(destructor:CIM.Message.CIMGetLatestMsgIdReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CIMGetLatestMsgIdReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CIMGetLatestMsgIdReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void CIMGetLatestMsgIdReq::Clear() {
// @@protoc_insertion_point(message_clear_start:CIM.Message.CIMGetLatestMsgIdReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&session_type_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
  _internal_metadata_.Clear<std::string>();
}

const char* CIMGetLatestMsgIdReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 user_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          user_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .CIM.Def.CIMSessionType session_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_session_type(static_cast<::CIM::Def::CIMSessionType>(val));
        } else
          goto handle_unusual;
        continue;
      // uint64 session_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CIMGetLatestMsgIdReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CIM.Message.CIMGetLatestMsgIdReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 user_id = 1;
  if (this->_internal_user_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_user_id(), target);
  }

  // .CIM.Def.CIMSessionType session_type = 2;
  if (this->_internal_session_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_session_type(), target);
  }

  // uint64 session_id = 3;
  if (this->_internal_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_session_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CIM.Message.CIMGetLatestMsgIdReq)
  return target;
}

size_t CIMGetLatestMsgIdReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CIM.Message.CIMGetLatestMsgIdReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 user_id = 1;
  if (this->_internal_user_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_user_id());
  }

  // uint64 session_id = 3;
  if (this->_internal_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_session_id());
  }

  // .CIM.Def.CIMSessionType session_type = 2;
  if (this->_internal_session_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_session_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CIMGetLatestMsgIdReq::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const CIMGetLatestMsgIdReq*>(
      &from));
}

void CIMGetLatestMsgIdReq::MergeFrom(const CIMGetLatestMsgIdReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CIM.Message.CIMGetLatestMsgIdReq)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_user_id() != 0) {
    _internal_set_user_id(from._internal_user_id());
  }
  if (from._internal_session_id() != 0) {
    _internal_set_session_id(from._internal_session_id());
  }
  if (from._internal_session_type() != 0) {
    _internal_set_session_type(from._internal_session_type());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CIMGetLatestMsgIdReq::CopyFrom(const CIMGetLatestMsgIdReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CIM.Message.CIMGetLatestMsgIdReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CIMGetLatestMsgIdReq::IsInitialized() const {
  return true;
}

void CIMGetLatestMsgIdReq::InternalSwap(CIMGetLatestMsgIdReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CIMGetLatestMsgIdReq, session_type_)
      + sizeof(CIMGetLatestMsgIdReq::session_type_)
      - PROTOBUF_FIELD_OFFSET(CIMGetLatestMsgIdReq, user_id_)>(
          reinterpret_cast<char*>(&user_id_),
          reinterpret_cast<char*>(&other->user_id_));
}

std::string CIMGetLatestMsgIdReq::GetTypeName() const {
  return "CIM.Message.CIMGetLatestMsgIdReq";
}


// ===================================================================

class CIMGetLatestMsgIdRsp::_Internal {
 public:
};

CIMGetLatestMsgIdRsp::CIMGetLatestMsgIdRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:CIM.Message.CIMGetLatestMsgIdRsp)
}
CIMGetLatestMsgIdRsp::CIMGetLatestMsgIdRsp(const CIMGetLatestMsgIdRsp& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  latest_msg_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    latest_msg_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_latest_msg_id().empty()) {
    latest_msg_id_.Set(from._internal_latest_msg_id(), 
      GetArenaForAllocation());
  }
  ::memcpy(&user_id_, &from.user_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&session_type_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
  // @@protoc_insertion_point(copy_constructor:CIM.Message.CIMGetLatestMsgIdRsp)
}

inline void CIMGetLatestMsgIdRsp::SharedCtor() {
latest_msg_id_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  latest_msg_id_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&user_id_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&session_type_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
}

CIMGetLatestMsgIdRsp::~CIMGetLatestMsgIdRsp() {
  // @@protoc_insertion_point(destructor:CIM.Message.CIMGetLatestMsgIdRsp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CIMGetLatestMsgIdRsp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  latest_msg_id_.Destroy();
}

void CIMGetLatestMsgIdRsp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void CIMGetLatestMsgIdRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:CIM.Message.CIMGetLatestMsgIdRsp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  latest_msg_id_.ClearToEmpty();
  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&session_type_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
  _internal_metadata_.Clear<std::string>();
}

const char* CIMGetLatestMsgIdRsp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 user_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          user_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .CIM.Def.CIMSessionType session_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_session_type(static_cast<::CIM::Def::CIMSessionType>(val));
        } else
          goto handle_unusual;
        continue;
      // uint64 session_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string latest_msg_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_latest_msg_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CIMGetLatestMsgIdRsp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CIM.Message.CIMGetLatestMsgIdRsp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 user_id = 1;
  if (this->_internal_user_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_user_id(), target);
  }

  // .CIM.Def.CIMSessionType session_type = 2;
  if (this->_internal_session_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_session_type(), target);
  }

  // uint64 session_id = 3;
  if (this->_internal_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_session_id(), target);
  }

  // string latest_msg_id = 4;
  if (!this->_internal_latest_msg_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_latest_msg_id().data(), static_cast<int>(this->_internal_latest_msg_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "CIM.Message.CIMGetLatestMsgIdRsp.latest_msg_id");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_latest_msg_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CIM.Message.CIMGetLatestMsgIdRsp)
  return target;
}

size_t CIMGetLatestMsgIdRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CIM.Message.CIMGetLatestMsgIdRsp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string latest_msg_id = 4;
  if (!this->_internal_latest_msg_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_latest_msg_id());
  }

  // uint64 user_id = 1;
  if (this->_internal_user_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_user_id());
  }

  // uint64 session_id = 3;
  if (this->_internal_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_session_id());
  }

  // .CIM.Def.CIMSessionType session_type = 2;
  if (this->_internal_session_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_session_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CIMGetLatestMsgIdRsp::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const CIMGetLatestMsgIdRsp*>(
      &from));
}

void CIMGetLatestMsgIdRsp::MergeFrom(const CIMGetLatestMsgIdRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CIM.Message.CIMGetLatestMsgIdRsp)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_latest_msg_id().empty()) {
    _internal_set_latest_msg_id(from._internal_latest_msg_id());
  }
  if (from._internal_user_id() != 0) {
    _internal_set_user_id(from._internal_user_id());
  }
  if (from._internal_session_id() != 0) {
    _internal_set_session_id(from._internal_session_id());
  }
  if (from._internal_session_type() != 0) {
    _internal_set_session_type(from._internal_session_type());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CIMGetLatestMsgIdRsp::CopyFrom(const CIMGetLatestMsgIdRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CIM.Message.CIMGetLatestMsgIdRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CIMGetLatestMsgIdRsp::IsInitialized() const {
  return true;
}

void CIMGetLatestMsgIdRsp::InternalSwap(CIMGetLatestMsgIdRsp* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &latest_msg_id_, lhs_arena,
      &other->latest_msg_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CIMGetLatestMsgIdRsp, session_type_)
      + sizeof(CIMGetLatestMsgIdRsp::session_type_)
      - PROTOBUF_FIELD_OFFSET(CIMGetLatestMsgIdRsp, user_id_)>(
          reinterpret_cast<char*>(&user_id_),
          reinterpret_cast<char*>(&other->user_id_));
}

std::string CIMGetLatestMsgIdRsp::GetTypeName() const {
  return "CIM.Message.CIMGetLatestMsgIdRsp";
}


// ===================================================================

class CIMGetMsgByIdReq::_Internal {
 public:
};

CIMGetMsgByIdReq::CIMGetMsgByIdReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  msg_id_list_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:CIM.Message.CIMGetMsgByIdReq)
}
CIMGetMsgByIdReq::CIMGetMsgByIdReq(const CIMGetMsgByIdReq& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      msg_id_list_(from.msg_id_list_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&user_id_, &from.user_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&session_type_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
  // @@protoc_insertion_point(copy_constructor:CIM.Message.CIMGetMsgByIdReq)
}

inline void CIMGetMsgByIdReq::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&user_id_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&session_type_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
}

CIMGetMsgByIdReq::~CIMGetMsgByIdReq() {
  // @@protoc_insertion_point(destructor:CIM.Message.CIMGetMsgByIdReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CIMGetMsgByIdReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CIMGetMsgByIdReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void CIMGetMsgByIdReq::Clear() {
// @@protoc_insertion_point(message_clear_start:CIM.Message.CIMGetMsgByIdReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  msg_id_list_.Clear();
  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&session_type_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
  _internal_metadata_.Clear<std::string>();
}

const char* CIMGetMsgByIdReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 user_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          user_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .CIM.Def.CIMSessionType session_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_session_type(static_cast<::CIM::Def::CIMSessionType>(val));
        } else
          goto handle_unusual;
        continue;
      // uint64 session_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated string msg_id_list = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_msg_id_list();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, nullptr));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CIMGetMsgByIdReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CIM.Message.CIMGetMsgByIdReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 user_id = 1;
  if (this->_internal_user_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_user_id(), target);
  }

  // .CIM.Def.CIMSessionType session_type = 2;
  if (this->_internal_session_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_session_type(), target);
  }

  // uint64 session_id = 3;
  if (this->_internal_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_session_id(), target);
  }

  // repeated string msg_id_list = 4;
  for (int i = 0, n = this->_internal_msg_id_list_size(); i < n; i++) {
    const auto& s = this->_internal_msg_id_list(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "CIM.Message.CIMGetMsgByIdReq.msg_id_list");
    target = stream->WriteString(4, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CIM.Message.CIMGetMsgByIdReq)
  return target;
}

size_t CIMGetMsgByIdReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CIM.Message.CIMGetMsgByIdReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string msg_id_list = 4;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(msg_id_list_.size());
  for (int i = 0, n = msg_id_list_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      msg_id_list_.Get(i));
  }

  // uint64 user_id = 1;
  if (this->_internal_user_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_user_id());
  }

  // uint64 session_id = 3;
  if (this->_internal_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_session_id());
  }

  // .CIM.Def.CIMSessionType session_type = 2;
  if (this->_internal_session_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_session_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CIMGetMsgByIdReq::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const CIMGetMsgByIdReq*>(
      &from));
}

void CIMGetMsgByIdReq::MergeFrom(const CIMGetMsgByIdReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CIM.Message.CIMGetMsgByIdReq)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  msg_id_list_.MergeFrom(from.msg_id_list_);
  if (from._internal_user_id() != 0) {
    _internal_set_user_id(from._internal_user_id());
  }
  if (from._internal_session_id() != 0) {
    _internal_set_session_id(from._internal_session_id());
  }
  if (from._internal_session_type() != 0) {
    _internal_set_session_type(from._internal_session_type());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CIMGetMsgByIdReq::CopyFrom(const CIMGetMsgByIdReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CIM.Message.CIMGetMsgByIdReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CIMGetMsgByIdReq::IsInitialized() const {
  return true;
}

void CIMGetMsgByIdReq::InternalSwap(CIMGetMsgByIdReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  msg_id_list_.InternalSwap(&other->msg_id_list_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CIMGetMsgByIdReq, session_type_)
      + sizeof(CIMGetMsgByIdReq::session_type_)
      - PROTOBUF_FIELD_OFFSET(CIMGetMsgByIdReq, user_id_)>(
          reinterpret_cast<char*>(&user_id_),
          reinterpret_cast<char*>(&other->user_id_));
}

std::string CIMGetMsgByIdReq::GetTypeName() const {
  return "CIM.Message.CIMGetMsgByIdReq";
}


// ===================================================================

class CIMGetMsgByIdRsp::_Internal {
 public:
};

void CIMGetMsgByIdRsp::clear_msg_list() {
  msg_list_.Clear();
}
CIMGetMsgByIdRsp::CIMGetMsgByIdRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  msg_list_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:CIM.Message.CIMGetMsgByIdRsp)
}
CIMGetMsgByIdRsp::CIMGetMsgByIdRsp(const CIMGetMsgByIdRsp& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      msg_list_(from.msg_list_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&user_id_, &from.user_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&session_type_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
  // @@protoc_insertion_point(copy_constructor:CIM.Message.CIMGetMsgByIdRsp)
}

inline void CIMGetMsgByIdRsp::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&user_id_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&session_type_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
}

CIMGetMsgByIdRsp::~CIMGetMsgByIdRsp() {
  // @@protoc_insertion_point(destructor:CIM.Message.CIMGetMsgByIdRsp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CIMGetMsgByIdRsp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CIMGetMsgByIdRsp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void CIMGetMsgByIdRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:CIM.Message.CIMGetMsgByIdRsp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  msg_list_.Clear();
  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&session_type_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(session_type_));
  _internal_metadata_.Clear<std::string>();
}

const char* CIMGetMsgByIdRsp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 user_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          user_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .CIM.Def.CIMSessionType session_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_session_type(static_cast<::CIM::Def::CIMSessionType>(val));
        } else
          goto handle_unusual;
        continue;
      // uint64 session_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .CIM.Def.CIMMsgInfo msg_list = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_msg_list(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CIMGetMsgByIdRsp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CIM.Message.CIMGetMsgByIdRsp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 user_id = 1;
  if (this->_internal_user_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_user_id(), target);
  }

  // .CIM.Def.CIMSessionType session_type = 2;
  if (this->_internal_session_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_session_type(), target);
  }

  // uint64 session_id = 3;
  if (this->_internal_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_session_id(), target);
  }

  // repeated .CIM.Def.CIMMsgInfo msg_list = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_msg_list_size()); i < n; i++) {
    const auto& repfield = this->_internal_msg_list(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CIM.Message.CIMGetMsgByIdRsp)
  return target;
}

size_t CIMGetMsgByIdRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CIM.Message.CIMGetMsgByIdRsp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .CIM.Def.CIMMsgInfo msg_list = 4;
  total_size += 1UL * this->_internal_msg_list_size();
  for (const auto& msg : this->msg_list_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint64 user_id = 1;
  if (this->_internal_user_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_user_id());
  }

  // uint64 session_id = 3;
  if (this->_internal_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_session_id());
  }

  // .CIM.Def.CIMSessionType session_type = 2;
  if (this->_internal_session_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_session_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CIMGetMsgByIdRsp::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const CIMGetMsgByIdRsp*>(
      &from));
}

void CIMGetMsgByIdRsp::MergeFrom(const CIMGetMsgByIdRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CIM.Message.CIMGetMsgByIdRsp)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  msg_list_.MergeFrom(from.msg_list_);
  if (from._internal_user_id() != 0) {
    _internal_set_user_id(from._internal_user_id());
  }
  if (from._internal_session_id() != 0) {
    _internal_set_session_id(from._internal_session_id());
  }
  if (from._internal_session_type() != 0) {
    _internal_set_session_type(from._internal_session_type());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CIMGetMsgByIdRsp::CopyFrom(const CIMGetMsgByIdRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CIM.Message.CIMGetMsgByIdRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CIMGetMsgByIdRsp::IsInitialized() const {
  return true;
}

void CIMGetMsgByIdRsp::InternalSwap(CIMGetMsgByIdRsp* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  msg_list_.InternalSwap(&other->msg_list_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CIMGetMsgByIdRsp, session_type_)
      + sizeof(CIMGetMsgByIdRsp::session_type_)
      - PROTOBUF_FIELD_OFFSET(CIMGetMsgByIdRsp, user_id_)>(
          reinterpret_cast<char*>(&user_id_),
          reinterpret_cast<char*>(&other->user_id_));
}

std::string CIMGetMsgByIdRsp::GetTypeName() const {
  return "CIM.Message.CIMGetMsgByIdRsp";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Message
}  // namespace CIM
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::CIM::Message::CIMMsgData*
Arena::CreateMaybeMessage< ::CIM::Message::CIMMsgData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CIM::Message::CIMMsgData >(arena);
}
template<> PROTOBUF_NOINLINE ::CIM::Message::CIMMsgDataAck*
Arena::CreateMaybeMessage< ::CIM::Message::CIMMsgDataAck >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CIM::Message::CIMMsgDataAck >(arena);
}
template<> PROTOBUF_NOINLINE ::CIM::Message::CIMMsgDataReadAck*
Arena::CreateMaybeMessage< ::CIM::Message::CIMMsgDataReadAck >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CIM::Message::CIMMsgDataReadAck >(arena);
}
template<> PROTOBUF_NOINLINE ::CIM::Message::CIMMsgDataReadNotify*
Arena::CreateMaybeMessage< ::CIM::Message::CIMMsgDataReadNotify >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CIM::Message::CIMMsgDataReadNotify >(arena);
}
template<> PROTOBUF_NOINLINE ::CIM::Message::CIMGetLatestMsgIdReq*
Arena::CreateMaybeMessage< ::CIM::Message::CIMGetLatestMsgIdReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CIM::Message::CIMGetLatestMsgIdReq >(arena);
}
template<> PROTOBUF_NOINLINE ::CIM::Message::CIMGetLatestMsgIdRsp*
Arena::CreateMaybeMessage< ::CIM::Message::CIMGetLatestMsgIdRsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CIM::Message::CIMGetLatestMsgIdRsp >(arena);
}
template<> PROTOBUF_NOINLINE ::CIM::Message::CIMGetMsgByIdReq*
Arena::CreateMaybeMessage< ::CIM::Message::CIMGetMsgByIdReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CIM::Message::CIMGetMsgByIdReq >(arena);
}
template<> PROTOBUF_NOINLINE ::CIM::Message::CIMGetMsgByIdRsp*
Arena::CreateMaybeMessage< ::CIM::Message::CIMGetMsgByIdRsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CIM::Message::CIMGetMsgByIdRsp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
